"""Shared shell scaffold for --to zoau and --to mvscmd.

Both targets emit the same outer structure: a #!/bin/sh header, per-step
comments, conditional if (( ... )); then ... fi blocks consolidated by
matching condition, and <step>_rc=$? capture for steps referenced
downstream. They differ only in how they render a single step's body.
"""

from __future__ import annotations

from collections.abc import Callable

from fromjcl.converters import _conditions
from fromjcl.models import Job, Step


def emit(job: Job, render_step: Callable[[Step], list[str]], header_tag: str) -> str:
    """Return the full shell script for the job.

    render_step(step) renders one step's command lines (no leading
    comment, no trailing rc capture; the scaffold adds those).
    """
    lines = [
        "#!/bin/sh",
        f"# Generated by fromjcl --to {header_tag}",
        f"# Job: {job.name}",
        f"# EXPERIMENTAL: --to {header_tag} output is best-effort. Review before running:",
        "# the bashlex-based flag validator catches typos, not semantic equivalence.",
        "",
    ]
    if job.symbols:
        lines.append("# WARNING: This job uses symbolic parameters:")
        for sym, val in job.symbols.items():
            lines.append(f"#   {sym}={val}")
        lines.append("# You may need to substitute these values manually.")
        lines.append("")

    referenced = _conditions.referenced_step_names(job.steps)
    for cond, steps in _conditions.group_consecutive_by_condition(job.steps):
        if cond is None:
            for step in steps:
                lines.extend(_emit_unconditional(step, render_step, referenced))
        else:
            lines.extend(_emit_conditional(cond, steps, render_step, referenced))
    return "\n".join(lines)


def _emit_unconditional(
    step: Step, render_step: Callable[[Step], list[str]], referenced: set[str]
) -> list[str]:
    out = [f"# Step: {step.name}"]
    out.extend(render_step(step))
    if step.name.lower() in referenced:
        out.append(f"{_conditions.shell_var(step.name)}=$?")
    out.append("")
    return out


def _emit_conditional(
    cond: str,
    steps: list[Step],
    render_step: Callable[[Step], list[str]],
    referenced: set[str],
) -> list[str]:
    out: list[str] = []
    warn = _conditions._approx_warning(cond)
    if warn:
        out.append(f"# WARNING: {warn}")
    out.append(f"# Steps: {', '.join(s.name for s in steps)}")
    out.append(f"if (( {_conditions.to_shell(cond)} )); then")
    body_has_command = False
    for step in steps:
        out.append(f"    # Step: {step.name}")
        for line in render_step(step):
            if line.strip():
                out.append(f"    {line}")
                if not line.lstrip().startswith("#"):
                    body_has_command = True
            else:
                out.append(line)
        if step.name.lower() in referenced:
            out.append(f"    {_conditions.shell_var(step.name)}=$?")
            body_has_command = True
    if not body_has_command:
        # bash if ... fi requires at least one command between then/fi.
        out.append("    :")
    out.append("fi")
    out.append("")
    return out
