"""Tabular CSV view of a parsed Job: one row per (step, dd, dataset)."""

import csv
import io
from typing import Any

from fromjcl.models import DD, Dataset, Job, Step

COLUMNS = [
    "job",
    "step",
    "condition",
    "program",
    "proc",
    "parm",
    "dd",
    "dsn",
    "disp",
    "disp_normal",
    "disp_abnormal",
    "recfm",
    "lrecl",
    "blksize",
    "space_type",
    "space_primary",
    "volumes",
    "sysout",
    "dummy",
    "instream",
]


def _empty_row() -> dict[str, str]:
    return dict.fromkeys(COLUMNS, "")


def _step_base(job: Job, step: Step) -> dict[str, str]:
    return {
        "job": job.name,
        "step": step.name,
        "condition": step.condition or "",
        "program": step.program or "",
        "proc": step.proc or "",
        "parm": step.parm or "",
    }


def _dd_base(step_base: dict[str, str], dd: DD) -> dict[str, str]:
    return {
        **step_base,
        "dd": dd.name,
        "sysout": dd.sysout or "",
        "dummy": "true" if dd.dummy else "",
        "instream": _format_instream(dd.instream),
    }


def _format_instream(instream: str | None) -> str:
    if not instream:
        return ""
    return "\\n".join(line.rstrip() for line in instream.split("\n")).strip("\\n")


def _row(dd_base: dict[str, str], ds: Dataset | None) -> dict[str, str]:
    row = _empty_row()
    row.update(dd_base)
    if ds is None:
        return row
    row["dsn"] = ds.dsn
    row["disp"] = ds.disposition.status
    row["disp_normal"] = ds.disposition.normal or ""
    row["disp_abnormal"] = ds.disposition.abnormal or ""
    if ds.dcb:
        row["recfm"] = ds.dcb.recfm or ""
        row["lrecl"] = str(ds.dcb.lrecl) if ds.dcb.lrecl else ""
        row["blksize"] = str(ds.dcb.blksize) if ds.dcb.blksize else ""
    if ds.space:
        row["space_type"] = ds.space.type
        row["space_primary"] = str(ds.space.primary)
    if ds.volumes:
        row["volumes"] = ",".join(ds.volumes)
    return row


def _step_rows(job: Job, step: Step) -> list[dict[str, str]]:
    """All rows generated by one step."""
    base = _step_base(job, step)
    if not step.dds:
        return [{**_empty_row(), **base}]

    rows: list[dict[str, str]] = []
    for dd in step.dds:
        dd_base = _dd_base(base, dd)
        if dd.datasets:
            rows.extend(_row(dd_base, ds) for ds in dd.datasets)
        else:
            rows.append(_row(dd_base, None))
    return rows


def convert(job: Job) -> str:
    """Render the job as CSV text, one row per (step, DD, dataset)."""
    buf = io.StringIO()
    writer: csv.DictWriter[Any] = csv.DictWriter(
        buf,
        fieldnames=COLUMNS,
        lineterminator="\n",
    )
    writer.writeheader()
    for step in job.steps:
        for row in _step_rows(job, step):
            writer.writerow(row)
    return buf.getvalue()
