"""Convert Job model to mvscmd shell commands."""

from fromjcl.models import Job, Step, DD, Dataset


def convert(job: Job) -> str:
    """Convert Job to mvscmd shell script."""
    lines = [
        "#!/bin/sh",
        "# Generated by fromjcl",
        f"# Job: {job.name}",
        "",
    ]

    # Warn about symbols
    if job.symbols:
        lines.append("# WARNING: This job uses symbolic parameters:")
        for sym, val in job.symbols.items():
            lines.append(f"#   {sym}={val}")
        lines.append("# You may need to substitute these values manually.")
        lines.append("")

    for step in job.steps:
        lines.append(f"# Step: {step.name}")
        cmd_lines = _build_mvscmd(step)
        lines.extend(cmd_lines)
        lines.append("")

    return "\n".join(lines)


def _build_mvscmd(step: Step) -> list[str]:
    """Build mvscmd command for a step."""
    result = []
    parts = ["mvscmd"]
    heredocs = []

    if step.program:
        parts.append(f"--pgm={step.program}")
    elif step.proc:
        result.append(f"# WARNING: PROC={step.proc} cannot be executed by mvscmd.")
        result.append(f"# Expand the PROC or find the program it calls.")
        parts.append("--pgm=UNKNOWN")

    if step.parm:
        parm = step.parm
        if parm.startswith("'") and parm.endswith("'"):
            parm = parm[1:-1]
        elif parm.startswith("('") and parm.endswith("')"):
            parm = parm[2:-2]
        parts.append(f"--args='{parm}'")

    for dd in step.dds:
        if "." in dd.name:
            dd_name = dd.name.split(".")[-1].lower()
        else:
            dd_name = dd.name.lower()

        if dd.instream is not None:
            parts.append(f"--{dd_name}=stdin")
            clean_data = "\n".join(
                line.rstrip() for line in dd.instream.rstrip("\n").split("\n")
            )
            heredocs.append((dd.name.replace(".", "_"), clean_data))
        elif dd.dummy:
            parts.append(f"--{dd_name}=dummy")
        elif dd.sysout:
            parts.append(f"--{dd_name}=*")
        elif dd.datasets:
            values = [_format_dataset(ds) for ds in dd.datasets]
            parts.append(f"--{dd_name}={':'.join(values)}")

    if len(parts) <= 2:
        cmd = " ".join(parts)
    else:
        cmd = parts[0] + " \\\n    " + " \\\n    ".join(parts[1:])

    result.append(cmd)

    for marker, content in heredocs:
        result[-1] += f" <<'END_{marker}'"
        result.append(content)
        result.append(f"END_{marker}")

    return result


def _format_dataset(ds: Dataset) -> str:
    """Format a dataset for mvscmd."""
    parts = [ds.dsn]
    status = ds.disposition.status.upper()

    if status == "OLD":
        parts.append("excl")
    elif status == "MOD":
        parts.append("mod")
    elif status == "NEW":
        parts.append("new")

        ds_type = ds.dataset_type
        if ds_type:
            parts.append(f"type={ds_type.lower()}")

        if ds.dcb:
            if ds.dcb.recfm:
                parts.append(f"recfm={ds.dcb.recfm}")
            if ds.dcb.lrecl:
                parts.append(f"lrecl={ds.dcb.lrecl}")
            if ds.dcb.blksize:
                parts.append(f"blksize={ds.dcb.blksize}")

        if ds.space:
            stype = ds.space.type.upper()
            parts.append(f"primary={ds.space.primary}{stype}")
            if ds.space.secondary:
                parts.append(f"secondary={ds.space.secondary}{stype}")
            if (
                ds.space.directory
                and ds_type
                and ds_type.lower() not in ("seq", "basic", "large")
            ):
                parts.append(f"dirblks={ds.space.directory}")

        if ds.volumes:
            parts.append(f"volumes={','.join(ds.volumes)}")

        if ds.disposition.normal:
            parts.append(f"normdisp={_map_disp(ds.disposition.normal)}")
        if ds.disposition.abnormal:
            parts.append(f"conddisp={_map_disp(ds.disposition.abnormal)}")

    return ",".join(parts)


def _map_disp(disp: str) -> str:
    """Map JCL disposition to mvscmd disposition."""
    disp = disp.upper()
    if disp == "CATLG":
        return "catalog"
    elif disp == "UNCATLG":
        return "uncatalog"
    return disp.lower()
