"""fromjcl/converters/mvscmd.py - Convert Job model to mvscmd shell commands."""

from fromjcl.models import Job
from fromjcl.converters.common import build_mvscmd_command


def convert(job: Job) -> str:
    """Convert Job to mvscmd shell script."""
    lines = [
        "#!/bin/sh",
        "# Generated by fromjcl",
        f"# Job: {job.name}",
        "",
    ]

    if job.symbols:
        lines.append("# WARNING: This job uses symbolic parameters:")
        for sym, val in job.symbols.items():
            lines.append(f"#   {sym}={val}")
        lines.append("# You may need to substitute these values manually.")
        lines.append("")

    for step in job.steps:
        lines.append(f"# Step: {step.name}")
        cmd_lines = build_mvscmd_command(step)
        lines.extend(cmd_lines)
        lines.append("")

    return "\n".join(lines)
