"""fromjcl/converters/zoau.py - Convert JCL steps to ZOAU shell commands."""

import re
from fromjcl.models import Job, Step, DD, Dataset
from fromjcl.converters.common import build_mvscmd_command


def convert(job: Job) -> str:
    """Convert a Job to ZOAU shell script."""
    lines = [
        "#!/bin/sh",
        "# Generated by fromjcl --to zoau",
        f"# Job: {job.name}",
        "",
    ]

    if job.symbols:
        lines.append("# WARNING: This job uses symbolic parameters:")
        for sym, val in job.symbols.items():
            lines.append(f"#   {sym}={val}")
        lines.append("# You may need to substitute these values manually.")
        lines.append("")

    for step in job.steps:
        lines.append(f"# Step: {step.name}")
        if step.condition:
            lines.append(f"# Conditional: {step.condition}")

        cmd_lines = _convert_step(step)
        lines.extend(cmd_lines)
        lines.append("")

    return "\n".join(lines)


def _convert_step(step: Step) -> list[str]:
    """Convert a single step to ZOAU commands."""
    if not step.program:
        if step.proc:
            return [
                f"# WARNING: PROC={step.proc} cannot be converted without expansion"
            ]
        return ["# No program specified"]

    pgm = step.program.upper()

    if pgm == "IEFBR14":
        return _convert_iefbr14(step)
    elif pgm == "IEBGENER":
        return _convert_iebgener(step)
    elif pgm == "IDCAMS":
        return _convert_idcams(step)
    elif pgm == "IEBCOPY":
        return _convert_iebcopy(step)
    elif pgm == "ISRSUPC":
        return _convert_isrsupc(step)
    elif pgm == "IEHLIST":
        return _convert_iehlist(step)
    elif pgm == "IEHPROGM":
        return _convert_iehprogm(step)
    else:
        return _fallback_mvscmd(step, f"No ZOAU equivalent for {pgm}")


def _convert_iefbr14(step: Step) -> list[str]:
    """Convert IEFBR14 step - analyze DDs for dataset operations."""
    result = []

    for dd in step.dds:
        dd_name = dd.name.split(".")[-1] if "." in dd.name else dd.name

        if dd_name.upper() in ("STEPLIB", "JOBLIB"):
            continue
        if dd.dummy or dd.sysout or dd.instream is not None:
            continue
        if not dd.datasets:
            continue

        for ds in dd.datasets:
            disp = ds.disposition

            if disp.status == "NEW" and disp.normal in ("CATLG", "KEEP"):
                result.append(f"# DD {dd_name}: Allocate dataset")
                result.append(_build_dtouch(ds))
            elif disp.normal == "DELETE" or disp.abnormal == "DELETE":
                if disp.status in ("OLD", "MOD", "SHR"):
                    result.append(f"# DD {dd_name}: Delete dataset")
                    result.append(f'drm "{ds.dsn}"')

    if not result:
        result.append("# IEFBR14 with no actionable DDs")

    return result


def _build_dtouch(ds: Dataset) -> str:
    """Build a dtouch command from dataset attributes."""
    args = []

    if ds.dataset_type:
        type_map = {
            "SEQ": "seq",
            "PDS": "pds",
            "PDSE": "pdse",
            "BASIC": "seq",
            "LARGE": "large",
        }
        mapped = type_map.get(ds.dataset_type.upper(), "pdse")
        args.append(f"-t{mapped}")

    if ds.dcb:
        if ds.dcb.lrecl:
            args.append(f"-l{ds.dcb.lrecl}")
        if ds.dcb.recfm:
            args.append(f"-r{ds.dcb.recfm}")
        if ds.dcb.blksize:
            args.append(f"-B{ds.dcb.blksize}")

    if ds.space:
        type_map = {"TRK": "T", "CYL": "C", "KB": "K", "MB": "M"}
        suffix = type_map.get(ds.space.type.upper(), "T")
        args.append(f"-s{ds.space.primary}{suffix}")

    if ds.volumes:
        args.append(f"-V{','.join(ds.volumes)}")

    args_str = " ".join(args)
    return f'dtouch {args_str} "{ds.dsn}"' if args_str else f'dtouch "{ds.dsn}"'


def _convert_iebgener(step: Step) -> list[str]:
    """Convert IEBGENER - dataset copy utility."""
    sysut1 = None
    sysut1_instream = None
    sysut2 = None
    sysut2_sysout = False

    for dd in step.dds:
        dd_name = (dd.name.split(".")[-1] if "." in dd.name else dd.name).upper()

        if dd_name == "SYSUT1":
            if dd.datasets:
                sysut1 = dd.datasets[0].dsn
            elif dd.instream is not None:
                sysut1_instream = dd.instream
        elif dd_name == "SYSUT2":
            if dd.datasets:
                sysut2 = dd.datasets[0].dsn
            elif dd.sysout:
                sysut2_sysout = True

    if sysut1_instream is not None and sysut2:
        cleaned = "\n".join(line.rstrip() for line in sysut1_instream.split("\n"))
        escaped = cleaned.replace("'", "'\\''")
        return [
            "# Write instream data to dataset",
            f"echo '{escaped}' | decho \"{sysut2}\"",
        ]

    if sysut1 and sysut2:
        return ["# Copy dataset", f'dcp "{sysut1}" "{sysut2}"']

    if sysut1 and sysut2_sysout:
        return ["# Copy dataset to stdout", f'dcat "{sysut1}"']

    return _fallback_mvscmd(step, "IEBGENER: Missing SYSUT1 or SYSUT2")


def _convert_idcams(step: Step) -> list[str]:
    """Convert IDCAMS - parse SYSIN for DELETE commands."""
    sysin_data = _get_sysin(step)
    if not sysin_data:
        return _fallback_mvscmd(step, "IDCAMS: No SYSIN instream data")

    result = []
    has_convertible = False

    for line in sysin_data.strip().split("\n"):
        line_upper = line.strip().upper()

        if line_upper.startswith("DELETE"):
            parts = line_upper.split()
            if len(parts) >= 2:
                dsn = parts[1].strip("'\"()")
                result.append("# IDCAMS DELETE")
                result.append(f'drm "{dsn}"')
                has_convertible = True
        elif line_upper.startswith("DEFINE"):
            result.append(f"# NOTE: IDCAMS DEFINE requires mvscmd")
        elif line_upper.startswith("LISTCAT"):
            result.append("# NOTE: IDCAMS LISTCAT - use 'dls' for equivalent")

    if has_convertible:
        return result

    return _fallback_mvscmd(step, "IDCAMS: No convertible commands found")


def _convert_iebcopy(step: Step) -> list[str]:
    """Convert IEBCOPY - PDS copy utility."""
    sysin_data = _get_sysin(step)
    dd_map = {dd.name.split(".")[-1].upper(): dd for dd in step.dds}

    sysin_is_dummy = any(
        (dd.name.split(".")[-1].upper() == "SYSIN" and dd.dummy) for dd in step.dds
    )

    if sysin_is_dummy or not sysin_data:
        sysut1_dd = dd_map.get("SYSUT1")
        sysut2_dd = dd_map.get("SYSUT2")
        if sysut1_dd and sysut2_dd and sysut1_dd.datasets and sysut2_dd.datasets:
            return [
                "# Copy PDS",
                f'dcp "{sysut1_dd.datasets[0].dsn}" "{sysut2_dd.datasets[0].dsn}"',
            ]

    if sysin_data:
        for line in sysin_data.strip().split("\n"):
            line_upper = line.strip().upper()
            if "COPY" in line_upper:
                outdd_match = re.search(r"OUTDD\s*=\s*([A-Z0-9]+)", line_upper)
                indd_match = re.search(r"INDD\s*=\s*\(?([A-Z0-9,]+)", line_upper)

                if outdd_match and indd_match:
                    out_name = outdd_match.group(1)
                    in_names = [n.strip() for n in indd_match.group(1).split(",")]

                    out_dd = dd_map.get(out_name)
                    in_dds = [dd_map.get(n) for n in in_names]

                    if (
                        out_dd
                        and out_dd.datasets
                        and all(d and d.datasets for d in in_dds)
                    ):
                        out_dsn = out_dd.datasets[0].dsn
                        if len(in_dds) == 1:
                            in_dsn = in_dds[0].datasets[0].dsn
                            return ["# Copy PDS", f'dcp "{in_dsn}" "{out_dsn}"']
                        else:
                            return _fallback_mvscmd(
                                step, "IEBCOPY: Merge operation requires mvscmd"
                            )

    return _fallback_mvscmd(step, "IEBCOPY: Could not parse SYSIN control statements")


def _convert_isrsupc(step: Step) -> list[str]:
    """Convert ISRSUPC (SuperC) - dataset comparison."""
    newdd = olddd = None
    sysin_data = _get_sysin(step)

    for dd in step.dds:
        dd_name = (dd.name.split(".")[-1] if "." in dd.name else dd.name).upper()

        if dd_name == "NEWDD" and dd.datasets:
            newdd = dd.datasets[0].dsn
        elif dd_name == "OLDDD" and dd.datasets:
            olddd = dd.datasets[0].dsn

    if not newdd or not olddd:
        return _fallback_mvscmd(step, "ISRSUPC: Missing NEWDD or OLDDD")

    opts = []
    if sysin_data:
        match = re.search(r"CMPCOLM[NO]?\s+(\d+):(\d+)", sysin_data.upper())
        if match:
            opts.append(f"-c{match.group(1)}:{match.group(2)}")

    opts_str = " ".join(opts)
    cmd = (
        f'ddiff {opts_str} "{newdd}" "{olddd}"'
        if opts_str
        else f'ddiff "{newdd}" "{olddd}"'
    )

    return ["# Compare datasets (RC=0 identical, RC=1 different)", cmd]


def _convert_iehlist(step: Step) -> list[str]:
    """Convert IEHLIST - list PDS members or VTOC."""
    sysin_data = _get_sysin(step)
    if not sysin_data:
        return _fallback_mvscmd(step, "IEHLIST: No SYSIN control statements")

    result = []

    for line in sysin_data.strip().split("\n"):
        line_upper = line.strip().upper()

        if line_upper.startswith("LISTPDS"):
            match = re.search(r"DSNAME\s*=\s*([A-Z0-9.$@#]+|\([^)]+\))", line_upper)
            if match:
                dsn = match.group(1).strip("()").split(",")[0].strip()
                result.extend(["# List PDS members", f'mls "{dsn}"'])

        elif line_upper.startswith("LISTVTOC"):
            match = re.search(
                r"VOL(?:UME)?\s*=\s*[A-Z0-9]+\s*=\s*([A-Z0-9]+)", line_upper
            )
            if match:
                result.extend(
                    ["# List volume table of contents", f"vtocls {match.group(1)}"]
                )

    if result:
        return result

    return _fallback_mvscmd(step, "IEHLIST: No convertible control statements")


def _convert_iehprogm(step: Step) -> list[str]:
    """Convert IEHPROGM - dataset/member rename and scratch."""
    sysin_data = _get_sysin(step)
    if not sysin_data:
        return _fallback_mvscmd(step, "IEHPROGM: No SYSIN control statements")

    result = []
    unsupported = []

    lines = _join_continuations(sysin_data)

    for line in lines:
        line_upper = line.strip().upper()

        if line_upper.startswith("RENAME"):
            dsn_match = re.search(r"DSNAME\s*=\s*([A-Z0-9.$@#]+)", line_upper)
            new_match = re.search(r"NEWNAME\s*=\s*([A-Z0-9.$@#]+)", line_upper)
            mem_match = re.search(r"MEMBER\s*=\s*([A-Z0-9$@#]+)", line_upper)

            if dsn_match and new_match:
                dsn, newname = dsn_match.group(1), new_match.group(1)
                if mem_match:
                    result.extend(
                        [
                            "# Rename PDS member",
                            f'mmv "{dsn}" {mem_match.group(1)} {newname}',
                        ]
                    )
                else:
                    result.extend(["# Rename dataset", f'dmv "{dsn}" "{newname}"'])

        elif line_upper.startswith("SCRATCH"):
            dsn_match = re.search(r"DSNAME\s*=\s*([A-Z0-9.$@#]+)", line_upper)
            mem_match = re.search(r"MEMBER\s*=\s*([A-Z0-9$@#]+)", line_upper)

            if dsn_match:
                dsn = dsn_match.group(1)
                if mem_match:
                    result.extend(
                        ["# Delete PDS member", f'mrm "{dsn}({mem_match.group(1)})"']
                    )
                else:
                    result.extend(["# Delete dataset", f'drm "{dsn}"'])

        elif line_upper.startswith(("CATLG", "UNCATLG", "BLDG")):
            unsupported.append(line_upper.split()[0])

    if unsupported:
        return _fallback_mvscmd(
            step, f"IEHPROGM: {', '.join(set(unsupported))} requires mvscmd"
        )

    if result:
        return result

    return _fallback_mvscmd(step, "IEHPROGM: No convertible control statements")


def _get_sysin(step: Step) -> str | None:
    """Extract SYSIN instream data from step."""
    for dd in step.dds:
        dd_name = dd.name.split(".")[-1] if "." in dd.name else dd.name
        if dd_name.upper() == "SYSIN" and dd.instream is not None:
            return dd.instream
    return None


def _join_continuations(sysin_data: str) -> list[str]:
    """Join continuation lines (non-blank in col 72)."""
    raw_lines = sysin_data.split("\n")
    joined = []
    current = ""

    for line in raw_lines:
        if len(line) >= 72 and line[71:72].strip():
            current += line[:71].rstrip()
        else:
            if current:
                current += line.strip()
                joined.append(current)
                current = ""
            elif line.strip():
                joined.append(line.strip())

    if current:
        joined.append(current)

    return joined


def _fallback_mvscmd(step: Step, reason: str) -> list[str]:
    """Build mvscmd fallback for unconvertible steps."""
    result = [f"# Fallback: {reason}"]
    result.extend(build_mvscmd_command(step))
    return result
