# SPDX-License-Identifier: Apache-2.0
"""Frozen snapshot of ZOAU 1.x command flags (55 verbs, 493 flags).

To refresh against a newer ZOAU release, run `man <verb>` on each verb
in FLAGS_BY_VERB below and reshape the synopsis lines into the existing
list structure.
"""

from __future__ import annotations

FLAGS: dict[str, frozenset[str]] = {
    "a2e": frozenset({"-F", "-d", "-f", "-h", "-q", "-t", "-v"}),
    "apfadm": frozenset(
        {"-A", "-F", "-J", "-M", "-P", "-R", "-d", "-f", "-h", "-i", "-j", "-l", "-v"}
    ),
    "dcat": frozenset({"-J", "-b", "-d", "-h", "-j", "-l", "-v"}),
    "dcp": frozenset({"-B", "-I", "-T", "-X", "-d", "-f", "-h", "-i", "-v"}),
    "ddiff": frozenset({"-C", "-Q", "-c", "-d", "-h", "-i", "-v"}),
    "ddls": frozenset({"-J", "-d", "-h", "-i", "-j", "-v"}),
    "decho": frozenset({"-a", "-d", "-f", "-h", "-v"}),
    "dgrep": frozenset({"-C", "-J", "-c", "-d", "-h", "-i", "-j", "-n", "-v"}),
    "dhead": frozenset({"-J", "-b", "-d", "-h", "-j", "-l", "-n", "-v"}),
    "dinfo": frozenset({"-J", "-T", "-b", "-d", "-h", "-j", "-l", "-s", "-u", "-v"}),
    "dls": frozenset(
        {
            "-F",
            "-H",
            "-J",
            "-S",
            "-T",
            "-U",
            "-V",
            "-a",
            "-b",
            "-d",
            "-h",
            "-i",
            "-j",
            "-l",
            "-m",
            "-p",
            "-q",
            "-s",
            "-t",
            "-u",
            "-v",
        }
    ),
    "dlsraw": frozenset({"-d", "-h", "-v"}),
    "dmod": frozenset(
        {"-J", "-b", "-c", "-d", "-e", "-f", "-h", "-i", "-j", "-l", "-m", "-r", "-s", "-v"}
    ),
    "dmv": frozenset({"-d", "-h", "-v"}),
    "drm": frozenset({"-F", "-d", "-f", "-h", "-n", "-v"}),
    "drmraw": frozenset({"-d", "-f", "-h", "-v"}),
    "dsed": frozenset({"-J", "-c", "-d", "-e", "-f", "-h", "-i", "-j", "-l", "-r", "-s", "-v"}),
    "dsfilter": frozenset({"-d", "-h", "-v"}),
    "dtail": frozenset({"-J", "-b", "-d", "-h", "-j", "-l", "-n", "-v"}),
    "dtouch": frozenset(
        {
            "-B",
            "-D",
            "-E",
            "-F",
            "-J",
            "-L",
            "-P",
            "-S",
            "-V",
            "-X",
            "-Y",
            "-a",
            "-b",
            "-c",
            "-d",
            "-e",
            "-h",
            "-j",
            "-k",
            "-l",
            "-m",
            "-r",
            "-s",
            "-t",
            "-u",
            "-v",
        }
    ),
    "dunzip": frozenset(
        {
            "--admin",
            "--bypass-acs",
            "--dataset",
            "--dataset-type",
            "--debug",
            "--exclude",
            "--help",
            "--import",
            "--include",
            "--keep-temporary-dataset",
            "--keyword",
            "--management-class",
            "--newhlq",
            "--no-rename",
            "--null-management-class",
            "--null-storage-class",
            "--overwrite",
            "--recatalog",
            "--rename",
            "--share",
            "--size",
            "--sphere",
            "--storage-class",
            "--target-gds",
            "--tmphlq",
            "--to-volume",
            "--tolerate",
            "--use-sms-for-temps",
            "--verbose",
            "--volume",
            "-D",
            "-H",
            "-I",
            "-N",
            "-Q",
            "-S",
            "-T",
            "-V",
            "-d",
            "-e",
            "-h",
            "-i",
            "-m",
            "-o",
            "-s",
            "-t",
            "-u",
            "-v",
        }
    ),
    "dwhence": frozenset({"-J", "-d", "-h", "-j", "-v"}),
    "dzip": frozenset(
        {
            "--compress",
            "--dataset",
            "--dataset-type",
            "--debug",
            "--exclude",
            "--force",
            "--help",
            "--keyword",
            "--management-class",
            "--no-compress",
            "--no-terse",
            "--overwrite",
            "--process-sys1",
            "--size",
            "--storage-class",
            "--terse",
            "--tmphlq",
            "--to-volume",
            "--tolerate",
            "--verbose",
            "--volume",
            "-D",
            "-Q",
            "-S",
            "-T",
            "-V",
            "-d",
            "-e",
            "-f",
            "-h",
            "-m",
            "-o",
            "-s",
            "-t",
            "-v",
        }
    ),
    "e2a": frozenset({"-F", "-d", "-f", "-h", "-q", "-t", "-v"}),
    "hlq": frozenset({"-d", "-h", "-v"}),
    "jcan": frozenset({"-d", "-h", "-v"}),
    "jdc": frozenset({"-h"}),
    "jls": frozenset({"-J", "-d", "-h", "-j", "-l", "-o", "-v"}),
    "jsub": frozenset({"-d", "-f", "-h", "-v"}),
    "llwhence": frozenset({"-d", "-h", "-v"}),
    "mls": frozenset({"-A", "-H", "-J", "-S", "-d", "-e", "-g", "-h", "-j", "-v", "-x"}),
    "mmv": frozenset({"-d", "-h", "-v"}),
    "mrm": frozenset({"-d", "-f", "-h", "-v"}),
    "mvscmd": frozenset(
        {
            "--archive",
            "--args",
            "--buildinfo",
            "--dd2",
            "--ddname",
            "--debug",
            "--help",
            "--info",
            "--json",
            "--newdd",
            "--olddd",
            "--outdd",
            "--pgm",
            "--prettyjson",
            "--steplib",
            "--sysin",
            "--syslib",
            "--sysout",
            "--sysprint",
            "--tmphlq",
            "--verbose",
            "-J",
            "-a",
            "-b",
            "-d",
            "-h",
            "-j",
            "-p",
            "-v",
        }
    ),
    "mvscmdauth": frozenset(
        {
            "--archive",
            "--args",
            "--buildinfo",
            "--dd2",
            "--ddname",
            "--debug",
            "--help",
            "--info",
            "--json",
            "--newdd",
            "--olddd",
            "--outdd",
            "--pgm",
            "--prettyjson",
            "--steplib",
            "--sysin",
            "--syslib",
            "--sysout",
            "--sysprint",
            "--tmphlq",
            "--verbose",
            "-J",
            "-a",
            "-b",
            "-d",
            "-h",
            "-j",
            "-p",
            "-v",
        }
    ),
    "mvscmdmsg": frozenset({"-d", "-h", "-v"}),
    "mvstmp": frozenset({"-c", "-d", "-h", "-v"}),
    "opercmd": frozenset({"-J", "-T", "-c", "-d", "-h", "-j", "-p", "-t", "-u", "-v", "-w"}),
    "parmgrep": frozenset({"-d", "-h", "-i", "-n", "-v"}),
    "parmwhence": frozenset({"-d", "-h", "-v"}),
    "pcon": frozenset(
        {
            "--all",
            "--allsys",
            "--day",
            "--debug",
            "--help",
            "--hour",
            "--json",
            "--month",
            "--prettyjson",
            "--recent",
            "--since",
            "--system",
            "--timediff",
            "--verbose",
            "--week",
            "--year",
            "-A",
            "-J",
            "-S",
            "-a",
            "-d",
            "-h",
            "-j",
            "-l",
            "-m",
            "-r",
            "-s",
            "-t",
            "-v",
            "-w",
            "-y",
        }
    ),
    "pdc": frozenset({"-Q", "-d", "-h", "-v"}),
    "pjdd": frozenset({"-J", "-d", "-h", "-i", "-j", "-v"}),
    "pll": frozenset({"-h", "-v"}),
    "pparm": frozenset({"-d", "-h", "-v"}),
    "pproc": frozenset({"-a", "-d", "-h"}),
    "procgrep": frozenset({"-d", "-h", "-i", "-n", "-v"}),
    "procwhence": frozenset({"-d", "-h", "-v"}),
    "relgen": frozenset({"-d", "-h", "-v"}),
    "smsraw": frozenset({"--ispfile", "-Q", "-d", "-h", "-v"}),
    "vf": frozenset({"-J", "-U", "-d", "-h", "-j", "-v"}),
    "vls": frozenset({"-d", "-h", "-l", "-m", "-v"}),
    "vtocls": frozenset({"-d", "-h", "-u", "-v"}),
    "zinfo": frozenset({"-J", "-a", "-d", "-h", "-j", "-p", "-t", "-v"}),
    "zoaversion": frozenset({"-b", "-c", "-d", "-h", "-j", "-v"}),
}
